<script setup>
import { onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { useFeedStore } from "../../stores/feed";
import { toggleCommentPanel } from "./comment-panel-state";
const feed = useFeedStore(); const route = useRoute(); const body = ref(""); const visibility = ref("全校可见"); const openComments = ref({}); const commentDrafts = ref({}); const editing = ref({});
onMounted(async () => { await Promise.all([feed.load(), feed.loadMine()]); });
async function publish() { if (!body.value.trim()) return; await feed.publish(body.value, visibility.value); body.value = ""; }
async function toggleComments(id) { if (!openComments.value[id]) await feed.loadComments(id); openComments.value = toggleCommentPanel(openComments.value, id); }
async function sendComment(id) { const value = commentDrafts.value[id]?.trim(); if (!value) return; await feed.comment(id, value); commentDrafts.value = { ...commentDrafts.value, [id]: "" }; }
async function save(post) { await feed.update(post.id, editing.value[post.id]); const next = { ...editing.value }; delete next[post.id]; editing.value = next; }
</script>
<template><section class="feed-workspace"><header class="feed-heading"><div><p class="eyebrow">CAMPUS FEED</p><h2>校园动态</h2></div><button @click="feed.personalOpen = !feed.personalOpen">{{ feed.personalOpen ? '返回公共动态' : '我的动态' }}</button></header><p v-if="feed.notice" class="feed-notice">{{ feed.notice }}</p>
<section v-if="!feed.personalOpen" class="feed-layout"><form class="post-composer" @submit.prevent="publish"><textarea v-model="body" placeholder="分享此刻的校园见闻…" rows="4"></textarea><footer><select v-model="visibility"><option>全校可见</option><option>好友可见</option><option>仅老师可见</option></select><button>发布动态</button></footer></form><article v-for="post in feed.posts" :key="post.id" class="post-card" :class="{ 'is-target': String(post.id) === String(route.query.post || '') }"><header><span>{{ post.author?.slice(0,1) }}</span><div><strong>{{ post.author }}</strong><small>{{ post.visibility }}</small></div></header><p>{{ post.body }}</p><footer><button :class="{liked:post.likedByCurrentUser}" @click="feed.like(post.id)">{{ post.likedByCurrentUser ? '已赞' : '赞' }} {{ post.likes }}</button><button @click="toggleComments(post.id)">评论 {{ post.comments }}</button></footer><section v-if="openComments[post.id]" class="comment-box"><article v-for="comment in feed.comments[post.id] || []" :key="comment.id"><strong>{{ comment.author }}</strong><p>{{ comment.body }}</p><small>{{ comment.time }}</small></article><form @submit.prevent="sendComment(post.id)"><input v-model="commentDrafts[post.id]" placeholder="写一条评论"/><button>发送</button></form></section></article></section>
<section v-else class="personal-posts"><p class="eyebrow">MY MOMENTS</p><article v-for="post in feed.mine" :key="post.id"><header><strong>{{ post.moderationStatus === 'approved' ? '已发布' : post.moderationStatus === 'rejected' ? '已拒绝' : '待审核' }}</strong><small>{{ post.visibility }}</small></header><p v-if="editing[post.id] === undefined">{{ post.body }}</p><textarea v-else v-model="editing[post.id]"></textarea><aside>{{ post.moderationStatus === 'pending' ? `审核原因：${post.moderationReason || '内容待审核'}。通过前不会出现在公共动态流。` : post.moderationStatus === 'rejected' ? `拒绝原因：${post.moderationReason || '请修改后重试'}` : '审核已通过，其他用户可以看到这条动态。' }}</aside><footer><template v-if="editing[post.id] === undefined"><button @click="editing={...editing,[post.id]:post.body}">编辑</button><button @click="feed.remove(post.id)">删除</button></template><template v-else><button @click="save(post)">保存</button><button @click="editing=Object.fromEntries(Object.entries(editing).filter(([id])=>Number(id)!==post.id))">取消</button></template></footer></article><p v-if="!feed.mine.length">你还没有发布过动态。</p></section></section></template>
